urfit-tech/lodestar-app-element

src/components/craft/CraftBoxModelInput.tsx, src/components/craft/CraftButton.tsx, src/components/craft/CraftColorPickerBlock.tsx
1. add primary color by using theme context
2. fix box model input decide
3. fix small button radio value
=> [FEATURE] use theme context

src/components/cards/ProgramPackageCard.tsx, src/components/collections/ProgramCollection.tsx, src/components/collections/ProgramPackageCollection.tsx, src/hasura.d.ts, src/helpers/index.ts, src/types/data.ts
- Show no price when program package was published but program package plan has not.
- text-decoration: line-through
=> [BUGFIX] filter price label with publishedAt

src/components/common/Carousel.tsx
- all used Carousel's component will be darggable
- modify in feature if necessary
=> [BUGFIX] modify carousel draggable

src/components/common/Carousel.tsx
- fix Carousel props
- i modify wrong position
=> [BUGFIX] fix Carousel props

src/components/common/BaseCarousel.tsx
- modify BaseCarousel draggable for other components
=> [BUGFIX] modify BaseCarousel draggable

src/components/inputs/InvoiceInput.tsx
=> [BUGFIX] modify InvoiceInput style

src/components/cards/CertificateContentCard.tsx, src/components/cards/CertificateImageCard.tsx, src/helpers/translation.ts, src/types/certificate.ts
There is a feature to preview certificate page in certificate admin page, so we need to share the certificate related component. 
I created 2 components, to make it easier to separate some features (e.g. download certificate image) and layout.
current usage: https://github.com/urfit-tech/lodestar-app-admin/pull/195
=> [Feature] Add Certificate content/image card

src/components/inputs/InvoiceInput.tsx, src/components/modals/CouponSelectionModal.tsx
- Trim the fields in InvoiceInput
- Trim coupon code input field
=> [FEATURE] Trim cart related input fields

src/contexts/AuthContext.tsx
=> refactor: get visitor first and logout adjustment

src/components/modals/CouponSelectionModal.tsx, src/helpers/translation.ts, src/hooks/util.ts
- add E_DUPLICATED_EXCHANGE translation
- use try catch for formatMessage error
=> [BUGFIX] fix coupon translation error

src/components/cards/ProjectCard.tsx, src/components/collections/ProjectCollection.tsx, src/hasura.d.ts, src/types/data.ts, src/types/element.ts
=> [BUGFIX] modify project card

src/components/collections/ProgramCollection.tsx, src/hasura.d.ts
- add craft's program collection sort
=> [FEATURE] add craft's program collection sort

src/components/inputs/ShippingInput.tsx
- fix shipping method not syncing
=> [BUGFIX] fix shipping method not syncing

src/components/modals/CheckoutProductModal.tsx
- add addToCart event in CheckoutProductModal
=> [BUGFIX] add addToCart event in CheckoutProductModal

src/contexts/AppContext.tsx, src/types/app.ts
1. add options and endedAt from GET_APP in hasura
=> feature: add options and endedAt

src/components/inputs/ShippingInput.tsx
=> bugfix: remove address prefix

src/components/common/Image.tsx
+ replace div tag with img tag
+ replace padding-top with height
=> feat:replace div with img

src/components/common/Tracking.tsx, src/hooks/tracking.ts
專為CwData的memberData，擴增會員卡訊息:
1.卡名 (title)
2.ID (id)
3.到期日 (ended_at)
4.開通日 (delivered_at)
=> feat:cw code adjustment for membership card

src/hooks/tracking.ts
=> fix:fix utc timezone issue

src/hooks/tracking.ts
- fix duplicate order product values
=> fix:fix duplicate order product values

src/types/app.ts
add program layout template module
=> feat:add program layout template module

src/components/cards/ProgramSecondaryCard.tsx, src/hooks/review.ts
=> feat: useReviewable

src/contexts/AuthContext.tsx, src/helpers/error.ts, src/helpers/index.ts
Expand the backend error response.
=> feat: extend return value of error

src/hooks/tracking.ts
event: 'register',
method: 'general' | 'checkout' | 'trial' ,
page: current page,
=> feat: register event

src/components/common/ReviewScoreStarRow.tsx
Trello 卡牌：https://trello.com/c/5stD1k3Q
=> fix: correct review count display in ReviewScoreStarRow component
